In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.svm import LinearSVC

In [2]:
data = pd.read_csv("D:\\practice_datasets\\classification\\iris\\Iris.csv")

In [3]:
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
5      6            5.4           3.9            1.7           0.4   
6      7            4.6           3.4            1.4           0.3   
7      8            5.0           3.4            1.5           0.2   
8      9            4.4           2.9            1.4           0.2   
9     10            4.9           3.1            1.5           0.1   
10    11            5.4           3.7            1.5           0.2   
11    12            4.8           3.4            1.6           0.2   
12    13            4.8           3.0            1.4           0.1   
13    14            4.3           3.0            1.1           0.1   
14    15            5.8           4.0            1.2           0.2   
15    16            5.7           4.4            1.5           0.4   
16    17            5.4           3.9            1.3           0.4   
17    18            5.1           3.5            1.4           0.3   
18    19            5.7           3.8            1.7           0.3   
19    20            5.1           3.8            1.5           0.3   
20    21            5.4           3.4            1.7           0.2   
21    22            5.1           3.7            1.5           0.4   
22    23            4.6           3.6            1.0           0.2   
23    24            5.1           3.3            1.7           0.5   
24    25            4.8           3.4            1.9           0.2   
25    26            5.0           3.0            1.6           0.2   
26    27            5.0           3.4            1.6           0.4   
27    28            5.2           3.5            1.5           0.2   
28    29            5.2           3.4            1.4           0.2   
29    30            4.7           3.2            1.6           0.2   
..   ...            ...           ...            ...           ...   
120  121            6.9           3.2            5.7           2.3   
121  122            5.6           2.8            4.9           2.0   
122  123            7.7           2.8            6.7           2.0   
123  124            6.3           2.7            4.9           1.8   
124  125            6.7           3.3            5.7           2.1   
125  126            7.2           3.2            6.0           1.8   
126  127            6.2           2.8            4.8           1.8   
127  128            6.1           3.0            4.9           1.8   
128  129            6.4           2.8            5.6           2.1   
129  130            7.2           3.0            5.8           1.6   
130  131            7.4           2.8            6.1           1.9   
131  132            7.9           3.8            6.4           2.0   
132  133            6.4           2.8            5.6           2.2   
133  134            6.3           2.8            5.1           1.5   
134  135            6.1           2.6            5.6           1.4   
135  136            7.7           3.0            6.1           2.3   
136  137            6.3           3.4            5.6           2.4   
137  138            6.4           3.1            5.5           1.8   
138  139            6.0           3.0            4.8           1.8   
139  140            6.9           3.1            5.4           2.1   
140  141            6.7           3.1            5.6           2.4   
141  142            6.9           3.1            5.1           2.3   
142  143            5.8           2.7            5.1           1.9   
143  144            6.8           3.2            5.9           2.3   
144  145            6.7           3.3            5.7           2.5   
145  146        

(array([-0.74244017, -0.62899918,  1.15181586,  0.60101999]),
 2.2423738499863397)
 99.33% accuracy

In [11]:
def predict(v,W,b):
    return W.dot(v) + b
def predict_all(V,W,b):
    P = []
    i = 0
    l = len(V)
    while (i<l):
        P.append(predict(V[i],W,b))
        i = i + 1
    return P
def cost(y_p,y_r):
    t = y_r*y_p
    if t >= 1:
        return 0
    else :
        return 1 - t
def total_cost(Y_p,Y_r):
    i = 0
    l = len(Y_r)
    summation = 0
    while (i<l):
        summation +=  cost(Y_p[i],Y_r[i])
        i  = i  + 1
    return summation
def fit(X,Y,W,b,learning_rate,regularizer,epochs,threshold = 0,output_when=100):
    iteration = 0
    new_W = W.copy()
    new_b = b
    D = len(W)
    P = predict_all(X,W,b)
    E = total_cost(P,Y)
    print(E)
    epoch = 0
    l = len(Y)
    while(E>threshold and iteration < epochs):
        i = 0
        while (i<l):
            d = 0
            #print("ffff")
            while (d < D):
                p = predict(X[i],new_W,new_b)
                if p*Y[i] < 1:
                    new_W[d] += learning_rate*(Y[i]*X[i][d] - 2*regularizer*new_W[d])
                else :
                    new_W[d] += learning_rate*(-2*regularizer*new_W[d])
                d += 1
            p = predict(X[i],W,b)
            if p*Y[i] < 1:
                    new_b += learning_rate*(-Y[i])
            i = i + 1
            #print(i)
        iteration += 1
        P = predict_all(X,new_W,new_b)
        E = total_cost(P,Y)
        if iteration % output_when == 0:
            print("Iteration:%d"%iteration)
            print(new_W,new_b)
            print("Total cost:%f"%E)
    return new_W,new_b

In [5]:
X = []
Y = []
for i in range(150):
    l = []
    l.append(data["SepalLengthCm"][i])
    l.append(data["SepalWidthCm"][i])
    l.append(data["PetalLengthCm"][i])
    l.append(data["PetalWidthCm"][i])
    X.append(l)
    if data["Species"][i] == 'Iris-setosa':
        Y.append(-1)
    else :
        Y.append(1)
X = np.array(X)
Y = np.array(Y)

In [26]:
W = np.random.rand(4)
b = np.random.randint(-10,10)



In [22]:
W = np.array([-0.74244017, -0.62899918, 1.15181586, 0.60101999] )    
b = 2.2423738499863397

In [27]:
new_W = W.copy()
new_b = b

In [32]:
W = new_W.copy()
b = new_b

In [28]:
new_W , new_b = fit(X,Y,new_W,new_b,learning_rate = 0.000001,regularizer =0.1,epochs = 10000,output_when = 100)

416.2788185031525
Iteration:100
[0.64958915 0.22540239 0.69214006 0.32634294] 2.005000000000699
Total cost:406.009467
Iteration:200
[0.62265105 0.20766297 0.68275779 0.32414721] 2.010000000001398
Total cost:395.771627
Iteration:300
[0.59579365 0.1899767  0.67340363 0.32195807] 2.0150000000020967
Total cost:385.565203
Iteration:400
[0.56901671 0.1723434  0.66407749 0.31977548] 2.0200000000027956
Total cost:375.390101
Iteration:500
[0.54231997 0.15476292 0.65477928 0.31759943] 2.0250000000034944
Total cost:365.246228
Iteration:600
[0.5157032  0.13723511 0.64550893 0.3154299 ] 2.0300000000041933
Total cost:355.133490
Iteration:700
[0.48916617 0.1197598  0.63626634 0.31326687] 2.0350000000048922
Total cost:345.051793
Iteration:800
[0.46270862 0.10233683 0.62705145 0.31111032] 2.040000000005591
Total cost:335.001045
Iteration:900
[0.43633033 0.08496606 0.61786415 0.30896023] 2.04500000000629
Total cost:324.981153
Iteration:1000
[0.41003106 0.06764733 0.60870438 0.30681657] 2.050000000006989

Iteration:8000
[-0.41955545 -0.59781367  0.54744406  0.32779268] 2.400000000055911
Total cost:14.866392
Iteration:8100
[-0.42072744 -0.60025423  0.55058842  0.32907694] 2.40500000005661
Total cost:14.610263
Iteration:8200
[-0.42222285 -0.6028295   0.55349235  0.3302879 ] 2.410000000057309
Total cost:14.357132
Iteration:8300
[-0.4232153  -0.60506154  0.55653137  0.3315144 ] 2.415000000058008
Total cost:14.128750
Iteration:8400
[-0.42425004 -0.60722058  0.55922619  0.33261128] 2.4200000000587067
Total cost:13.928754
Iteration:8500
[-0.42498604 -0.60911598  0.56188456  0.33368185] 2.4250000000594056
Total cost:13.755662
Iteration:8600
[-0.42587619 -0.61107288  0.56441981  0.33471562] 2.4300000000601045
Total cost:13.584399
Iteration:8700
[-0.4272863  -0.61323632  0.56658335  0.33564009] 2.4350000000608034
Total cost:13.413575
Iteration:8800
[-0.42842721 -0.61521142  0.56881314  0.33657738] 2.4400000000615023
Total cost:13.255628
Iteration:8900
[-0.42932045 -0.61701299  0.57110331  0.33752

In [30]:
correct = 0
for i in range(150):
    p = predict(X[i],new_W,new_b)
    if p > 0 and Y[i] == 1 :
        correct += 1
    elif p < 0 and Y[i] == -1 :
        correct += 1
print("%f"%(correct/150))

1.000000


In [190]:
np.random.ran

AttributeError: module 'numpy.random' has no attribute 'ran'

In [124]:
a  , b = new_W , new_b 

In [188]:
0.993333 * 150

148.99995

In [189]:
149/150

0.9933333333333333

In [190]:
new_W , new_b

(array([-0.74244017, -0.62899918,  1.15181586,  0.60101999]),
 2.2423738499863397)

In [4]:
svc = LinearSVC()

In [7]:
a = svc.fit(X,Y)

In [8]:
a.coef_,a.intercept_

(array([[-0.18424379, -0.45122581,  0.80794244,  0.45071296]]),
 array([-0.10956464]))

In [17]:
p = a.predict(X)

In [16]:
Y

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [18]:
np.where(p != Y)

(array([], dtype=int64),)

In [20]:
p == Y

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [31]:
new_W , new_b

(array([-0.44060429, -0.63763987,  0.59289511,  0.34691452]),
 2.500000000069889)

In [32]:
a.coef_,a.intercept_

(array([[-0.18424379, -0.45122581,  0.80794244,  0.45071296]]),
 array([-0.10956464]))

In [33]:
predict_all(X,new_W,new_b)

[-1.0793853773833857,
 -0.6724445822496681,
 -0.7711412104048021,
 -0.5447377721293258,
 -1.099088935980514,
 -1.2193711775099025,
 -0.7606277937527568,
 -0.9122714500687867,
 -0.3883784503827603,
 -0.7116105105279367,
 -1.2798051280082485,
 -0.7648610813513166,
 -0.6630756051350923,
 -0.6206419936262408,
 -1.8252073388303396,
 -1.7889514234436712,
 -1.456529221353411,
 -1.0446939256196646,
 -1.3224799284330868,
 -1.176696377085062,
 -0.9699341436602196,
 -1.0782409378459166,
 -1.1600052643108358,
 -0.6699145142587408,
 -0.5869925484686855,
 -0.5979259892062103,
 -0.7835990355804676,
 -1.0641562953008052,
 -1.0596818187862573,
 -0.5932726775221706,
 -0.5735691189250423,
 -1.0191302620545324,
 -1.4814316719170755,
 -1.7019750052245461,
 -0.7116105105279367,
 -0.9626120080005687,
 -1.3149166038574487,
 -0.7116105105279367,
 -0.5114319488190628,
 -0.9563318789470832,
 -1.0599230077022455,
 -0.07445301360566337,
 -0.6389599237699128,
 -0.7779801195284515,
 -0.904846881477833,
 -0.593692701